plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# SEO stuff
author: Hunter Pickett
summary: My personal website, mainly centered around tech and ham radio. 
lang: en
locale: en_NZ
#url: "https://zl2edh.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20